# Generated by Django 2.1.4 on 2019-02-09 12:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('name', models.CharField(max_length=32)),
                ('desc', models.CharField(max_length=256)),
                ('loc', models.CharField(max_length=64)),
                ('eid', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('confirmed', models.IntegerField(default=0)),
                ('initTime', models.DateTimeField(default=datetime.datetime(2019, 2, 9, 12, 42, 56, 3042))),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('name', models.CharField(max_length=64)),
                ('gid', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('groupType', models.CharField(choices=[('private', 'Private Group'), ('public', 'Public Group')], max_length=7)),
                ('events', models.ManyToManyField(related_name='group_events', to='backend.Event')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=32)),
                ('uid', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('pwdHash', models.BinaryField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='group_members', to='backend.User'),
        ),
        migrations.AddField(
            model_name='group',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_owner', to='backend.User'),
        ),
        migrations.AddField(
            model_name='event',
            name='confirmedMembers',
            field=models.ManyToManyField(related_name='group_confirmed_members', to='backend.User'),
        ),
        migrations.AddField(
            model_name='event',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_owner', to='backend.User'),
        ),
    ]
