# Generated by Django 2.1.4 on 2019-02-09 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expoPushToken',
            field=models.CharField(default='exit', max_length=22),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='initTime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
