# Generated by Django 2.1.4 on 2019-02-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20190209_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expoPushToken',
            field=models.CharField(max_length=64),
        ),
    ]
